services:
  token:
    build:
      context: token-service
      dockerfile: ../Dockerfile
    image: token-service
    container_name: ${TOKEN_HOST}
    ports:
      - '${TOKEN_PORTS}'
  bookmark:
    build:
      context: bookmarks-service
      dockerfile: ../Dockerfile
    image: bookmark
    container_name: ${BOOKMARK}
    depends_on:
      - bookmark-db
      - token
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${BOOKMARK_DB}:5432/bookmarks
      - SPRING_DATASOURCE_USERNAME=bmks
      - SPRING_DATASOURCE_PASSWORD=skram
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - TOKEN_HOST=${TOKEN_HOST}
    ports:
      - '${BOOKMARK_PORTS}'
    volumes:
      - bookmark_db:/var/lib/postgresql/data
  session-service:
    build: .
    links:
      - redis
    ports:
      - "8085:8085"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - TOKEN_HOST=${TOKEN_HOST}
      - TOKEN_PORT=${TOKEN_PORT}
  bookmark-db:
    image: 'postgres:15-alpine'
    container_name: ${BOOKMARK_DB}
    environment:
      - POSTGRES_DB=bookmarks
      - POSTGRES_USER=bmks
      - POSTGRES_PASSWORD=skram
  redis:
    container_name: redis
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_db:/data
volumes:
  bookmark_db:
  redis_db:
